name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod

    - name: Check out
      uses: actions/checkout@v3

    - name: Build
      run: go build -v

    - name: Test
      run: |
        go test -v -bench . -race
        GOARCH=386 go test -v
